version: "3.8"

services:      
  web-app:         
    image: "web-app"
    ports:
      - "4300:80"

    depends_on:
      - api-server 

  api-server:
    image: "api"
    ports:
      - "8080:8080"