@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "User", "Usuario con acceso al karaoke")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Karaoke", "Sistema de karaoke")

Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml